### ISSUE TITLE
events list backend

### ISSUE THREAD

**Issue by mjrb** [HackRU/OneAppFlutter#15]
- [x] put images in misc
- [x] annoy heman/ get prod endpoint work

**Comment by mjrb** [comment]
prod endpoint works. @dhruvilp pls send images if they are ready

**Comment by dhruvilp** [comment]
ok sending

**Comment by dhruvilp** [comment]
sent in Discord

**Comment by mjrb** [comment]
actually doing assets instead of bucket.
