### ISSUE TITLE
loading indicator on Scanning Page

### ISSUE THREAD

**Issue by dhruvilp** [HackRU/OneAppFlutter#20]
For scanner, consider pressing QRScanner button -> app asks for permission -> accept ->  scanner is on -> don't scan -> press backward button -> loading indicator pops up one on other like 2-3. So can you take a look at it?

**Comment by mjrb** [comment]
there was a similar issue with the login page. I fixed it by finding the point in between whatever Future we waitng for resolving and doing a navigator.pop to remove the spinner before pushing the home page.
