### ISSUE TITLE
caching events

### ISSUE THREAD

**Issue by mjrb** [HackRU/OneAppFlutter#22]
should probably use a similar stream concept to try loading cache and then network. maybe it might be a good idea to keep an expiration in memory for the event cache and the announcement cache. for announcements lcs will only update every 10 minutes and the events probably wont update that much day of so 30 mins - 10 minute Time To Live should be fine too. @dhruvilp or @SeanTaylorLane let me know what you think about adding TTL to these caches.

**Comment by dhruvilp** [comment]
yeah, 30 mins for events should be fine but for announcements, I think we should have ~< 5mins b/c we sent out announcements quite often (especially when we events in half an hour, etc..).  @mjrb
