### ISSUE TITLE
Create a Pub Library to handle backend stuff

### ISSUE THREAD

**Issue by dhruvilp** [HackRU/OneAppFlutter#46]
It will be uploaded to pub.dev so can be easily accessed in our project.

**Comment by mjrb** [comment]
I kinda want to help work on this. the start would likely to be to take the hackru and misc service module thingies and break them out into their own package

**Comment by dhruvilp** [comment]
@mjrb yeah sure. We'll talk today.

**Comment by mjrb** [comment]
created the [repo](https://github.com/HackRU/dart-lcs-client). if you make an account for pub make sure to dm me credentials

**Comment by dhruvilp** [comment]
Perfect!
