### ISSUE TITLE
QR scanner business logic

### ISSUE THREAD

**Issue by dhruvilp** [HackRU/OneAppFlutter#64]
**Describe the bug**
QR Scanner was making 2 requests per scan to the DB (maybe fixed now but double check)

**To Reproduce**
1. Open the scanner and scan a QR code
2. Insert a print statement to ensure how many requests we're making per scan

**Expected behavior**
Should only make 1 request per QR code scan

**Additional context**
We might implement the BloC pattern for QR Scanner so do research on Flutter BloC and implement it so we could avoid this kind of bugs.

**Comment by shivanmodha** [comment]
Done!
