### ISSUE TITLE
Reward for saving plastic

### ISSUE THREAD

**Issue by mjrb** [HackRU/OneAppFlutter#69]
We're thinking of having a setup where a hacker could scan a qr at the water fountain and it would give them credit for reusing a water bottle.

**Describe the solution you'd like**
We can reuse some components from the QR scanner for event scanning but it should be its own tab. For storing  the data we will need a new lcs endpoint, but for now this can be mocked, or use the update endpoint with `{$push: {water_score: <the QR code>}}`

**Additional context**
We may not make a new endpoint, there is still some details to be discussed.

**Comment by shivanmodha** [comment]
@mjrb I think you mentioned this is now a new scanning category?
