### ISSUE TITLE
QR User Info

### ISSUE THREAD

**Issue by shivanmodha** [HackRU/OneAppFlutter#70]
**Is your feature request related to a problem? Please describe.**
Want to see user info upon scan

**Describe the solution you'd like**
Once a user is scanned, the scanner person should be able to see user registration status, and name

**Comment by dhruvilp** [comment]
Got it, I'll try to add this in next update for demo (April 14th one).

**Comment by man1han** [comment]
Resolved in the latest functionality update. Re-scanning not required. The user's name and status will be displayed on dashboard upon login.
