### ISSUE TITLE
Filter Announcements by Topic

### ISSUE THREAD

**Issue by dhruvilp** [HackRU/OneAppFlutter#73]
**Describe the solution you'd like**
Allow users to filter announcements by topic (ex: food, prizes, tech-talk, etc)

**Additional context**
Add `material choice chips` selection one row (make it horizontal scrollview like continuous) below timer banner so users can filter announcements by specific topic

**Comment by mjrb** [comment]
How will you determine what topic an announcement is for?

**Comment by PJprogrammer** [comment]
> How will you determine what topic an announcement is for?
Some kind of text search for now. However, it could be inaccurate. In the future, we can have the backend classify the announcements.
