### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by PJprogrammer** [HackRU/OneAppFlutter#75]
**Is your feature request related to a problem? Please describe.**
Have a way to turn on/off push notifications for a particular firebase topic

**Describe the solution you'd like**
Settings Page

Technical Implementation:
- Accessible from drawer
- ListTile CheckBox for subscribing/unsubscribing to different firebase topics

**Describe alternatives you've considered**
Could have a separate page just dedicated for this

**Additional context**
More options will be added to Settings Page in the future. 

Have something in Events Page that links to Settings Page.

**Comment by mjrb** [comment]
You may also want to consider having something on the events page so people know they can unsubscribe/subscibe to specific events
