### ISSUE TITLE
Events Page Loading Indicator Keep Loading on Error

### ISSUE THREAD

**Issue by dhruvilp** [HackRU/OneAppFlutter#79]
**Describe the bug**
Events Page Loading Indicator Keep Loading on Error

**To Reproduce**
Go to `Events Tab`

**Expected behavior**
Loading Indicator Keep Loading on Error or `No-data-found`

**Fix/Suggestion**
Display appropriate error message like we do on the `Announcement Tab`

**Comment by JScheire** [comment]
Are you sure it's an issue with the loading indicator?

https://github.com/HackRU/OneAppFlutter/blob/4fd40f0db0b2a704c58c26f6b3f947b3e4f0de51/lib/services/hackru_service.dart#L111

This request returns status 500, I don't think it's an issue on our end.
